version: '3.9'

services:

  mysql:
    image: mysql
    container_name: mysql1
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql_scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${ROOTPW}
      - MYSQL_USER=${UNAME}
      - MYSQL_PASSWORD=${USERPW}
      - TZ=America/Toronto
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55


volumes:
  redis_cache:
  mysql_data: