# Generated by Django 4.2 on 2023-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_generaldata_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='count_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='country',
            field=models.CharField(max_length=40),
        ),
    ]
